# Generated by Django 4.2.3 on 2024-06-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLHealthAI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_page',
            old_name='name',
            new_name='nameform',
        ),
    ]
