# Generated by Django 4.2.3 on 2024-06-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLHealthAI', '0002_rename_name_contact_page_nameform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_page',
            new_name='Contact_page_model',
        ),
    ]
